### ISSUE TITLE
Display As: button - Should be hidden if configuration is set to list or gird

### ISSUE THREAD

**Issue by jdayus** [SoftwareAG/cumulocity-asset-viewer-widget-plugin#2]
![image](https://github.com/SoftwareAG/cumulocity-asset-viewer-widget-plugin/assets/94570594/fbb90fee-f864-4481-94d9-da24f3e11f9b)

Hiding these controls would be helpful since the ‘list display’ button does not do anything and the ‘Attention Required' switch only filters based on active alerts which is not really in context for this page

**Comment by DarpanLalani** [comment]
Button issue fixed in 1.0.3.   "Attention Required" is useful filter specifically you have many devices/assets.
